Update js_formatter.py
Plugin broke today and console has this line.  When I paste back in the pull request, plugin works.





Writing file /Users/tfuertes/Library/Application Support/Sublime Text 2/Packages/JsFormat/jsbeautifier/__init__.py with encoding UTF-8
Traceback (most recent call last):
  File "./sublime_plugin.py", line 362, in run_
  File "./js_formatter.py", line 58, in run
  File "./jsbeautifier/__init__.py", line 99, in beautify
    
  File "./jsbeautifier/__init__.py", line 218, in beautify
    
  File "./jsbeautifier/__init__.py", line 255, in unpack
    
ImportError: No module named unpackers